package apps;

import java.util.List;

import tables.HashArrayTable;
import tables.SearchTable;
import tables.Table;

/**
 * Sandbox for execution of arbitrary code
 * for testing or grading purposes.
 * <p>
 * Modify the code for your use case.
 */
@Deprecated
public class Sandbox {
	public static void main(String[] args) {
		HashArrayTable table = new HashArrayTable(
			"sandbox_1",
			List.of("letter", "order", "vowel"),
			List.of("string", "integer", "boolean"),
			0
		);
//		table.put(List.of("alpha", 1, true));
//		table.put(List.of("beta", 2, false));
//		table.put(List.of("gamma", 3, false));
//		table.put(List.of("delta", 4, false));
//		table.put(List.of("tau", 19, false));
//		table.put(List.of("pi", 16, false));
//		table.put(List.of("omega", 24, true));
		table.remove("c");
		table.put(List.of("a8", 2171, false));
		table.put(List.of("b0", 2, true));
		table.put(List.of("bc", 0, false));
		table.get("a");
		table.put(List.of("d", 7344, false));
		table.remove("d");
		table.put(List.of("ff", 260, false));
		table.put(List.of("b", 0, false));
		table.remove("bb28");
		table.put(List.of("b9", 456962, false));
		table.put(List.of("f", 0, false));
		table.remove("a");
		table.get("c");
		table.put(List.of("c5", 0, true));
		table.remove("c4d");
		table.put(List.of("c894", 2, true));
		table.put(List.of("b", 0, true));
		table.put(List.of("b252", 3017, true));
		table.put(List.of("f", 13018, true));
		table.put(List.of("d5", 0, true));
		table.put(List.of("e86f", 2, false));
		table.put(List.of("c1", 515, true));
		table.put(List.of("c", 476, false));
		table.put(List.of("c", 106, true));
		table.put(List.of("a", 0, false));
		table.put(List.of("f", 2, false));
		table.remove("c");
		table.put(List.of("d", 0, false));
		table.remove("a");
		table.put(List.of("f", 0, true));
		table.put(List.of("d", 0, false));
		table.remove("f");
		table.remove("da0");
		table.put(List.of("f10", 482, false));
		table.put(List.of("da46", 0, false));
		table.get("d21c");
		table.get("c");
		table.put(List.of("b5", 1038, false));
		table.put(List.of("a", 0, true));
		table.get("e7");
		table.put(List.of("ee7", 0, false));
		table.put(List.of("c", 0, true));
		table.get("f");
		table.put(List.of("ac", 0, true));
		table.put(List.of("b5d", 0, false));
		table.put(List.of("ee", 0, true));
		table.get("c5");
		table.put(List.of("d45", 1497, true));
		table.put(List.of("d", 152, false));
		table.put(List.of("e", 0, true));
		table.put(List.of("c", 188, false));
		table.put(List.of("a", 2, true));
		table.remove("c8");
		table.remove("f");
		table.remove("a");
		table.get("e8");
		table.put(List.of("a", 20, false));
		table.remove("c73");
		table.put(List.of("f", 0, false));
		table.get("e");
		table.put(List.of("b", 2290, true));
		table.get("efd");
		table.put(List.of("e2", 20, true));
		table.put(List.of("ac9f", 1710, true));
		table.put(List.of("ee58", 0, true));
		table.put(List.of("c", 1137, true));
		table.put(List.of("acd", 3, true));
		table.put(List.of("f", 1773, true));
		table.put(List.of("a", 0, false));
		table.put(List.of("c2", 0, false));
		table.put(List.of("a", 16, true));
		table.get("c7");
		table.remove("dde");
		table.remove("f67");
		table.put(List.of("ae8a", 0, false));
		table.put(List.of("e9", 6, false));
		table.put(List.of("a", 0, true));
		table.put(List.of("ac", 259423, false));
		table.put(List.of("aa", 86, false));
		table.put(List.of("b", 0, true));
		table.put(List.of("d9d", 0, true));
		table.put(List.of("f", 248, true));
		table.put(List.of("a8", 5089, false));
		table.put(List.of("b9cf", 1788, false));
		table.put(List.of("b741", 0, false));
		table.put(List.of("b61", 0, false));
		table.put(List.of("c", 1172, true));
		table.put(List.of("c714", 0, true));
		table.remove("e00");
		table.put(List.of("b34", 0, true));
		table.put(List.of("a", 0, true));
		table.put(List.of("a7c", 0, true));
		table.remove("d10");
		table.put(List.of("d294", 14220, true));
		table.remove("b8");
		table.put(List.of("e08", 3124, true));
		table.put(List.of("dd", 0, true));
		table.put(List.of("d", 535, true));
		table.put(List.of("e4", 2, true));
		table.remove("c7");
		table.remove("d");
		table.put(List.of("d", 0, true));
		table.put(List.of("d7", 24, true));
		table.put(List.of("ec", 280, false));
		table.remove("b1");
		table.remove("ce9");
		table.remove("e");
		table.remove("e3");
		table.put(List.of("c", 1231, false));
		table.remove("c17");
		table.put(List.of("f", 25, true));
		table.remove("c1cd");
		table.put(List.of("e", 213, true));
		table.put(List.of("d", 1537, true));
		table.get("c3e");
		table.put(List.of("f2d", 0, true));
		table.put(List.of("dd", 0, false));
		table.remove("ca");
		table.put(List.of("e", 7, false));
		table.put(List.of("e", 130, true));
		table.put(List.of("d0", 48, false));
		table.put(List.of("a", 1, false));
		table.put(List.of("aed3", 0, true));
		table.put(List.of("af", 141, false));
		table.put(List.of("b0db", 3897, false));
		table.put(List.of("ada", 0, false));
		table.put(List.of("cc0", 101, false));
		table.remove("ba");
		table.put(List.of("d", 4790, true));
		table.remove("f");
		table.remove("b02");
		table.put(List.of("e", 68995, false));
		table.remove("a3");
		table.put(List.of("e0", 0, false));
		table.remove("b");
		table.put(List.of("c1e", 15753, true));
		table.put(List.of("a4", 2, false));
		table.put(List.of("efc", 0, true));
		table.put(List.of("b80", 255686, false));
		table.remove("db57");
		table.put(List.of("a", 0, false));
		table.put(List.of("ee", 7408, true));
		table.remove("f2");
		table.remove("c");
		table.put(List.of("b", 0, true));
		table.put(List.of("c3", 1049, true));
		table.get("a1f");
		table.put(List.of("a", 7, true));
		table.put(List.of("dc57", 0, true));
		table.remove("a19");
		table.put(List.of("c8", 2, false));
		table.put(List.of("c", 0, false));
		table.put(List.of("aa7", 5, false));
		table.get("e");
		table.remove("c4");
		table.put(List.of("a9", 0, true));
		table.put(List.of("b", 19406, true));
		table.put(List.of("c", 0, true));
		table.put(List.of("e9", 851, true));
		table.remove("b");
		table.put(List.of("bd", 0, true));
		table.put(List.of("a5", 0, true));
		table.put(List.of("cc", 0, true));
		table.put(List.of("c", 0, false));
		table.put(List.of("c", 0, true));
		table.put(List.of("d", 0, false));
		table.put(List.of("e3", 1833, false));
		table.get("f3");
		table.put(List.of("b", 105, true));
		table.put(List.of("f", 2837, true));
		table.remove("c");
		table.put(List.of("b32", 4, true));
		table.get("a3");
		table.remove("d");
		table.put(List.of("d", 28640, true));
		table.put(List.of("f5", 0, false));
		table.put(List.of("d2f", 2, false));
		table.remove("f1");
		table.put(List.of("ae2d", 15, false));
		table.put(List.of("bca", 1, true));
		table.remove("c");
		table.put(List.of("c8d", 94, true));
		table.get("bbf");
		table.put(List.of("a", 0, false));
		table.put(List.of("d6", 0, true));
		table.put(List.of("f021", 127, false));
		table.put(List.of("dd6", 1116, true));
		table.put(List.of("e", 0, true));
		table.put(List.of("a", 1105, true));
		table.remove("a73");
		table.put(List.of("cb", 31384, false));
		table.put(List.of("e8", 5158, false));
		table.put(List.of("de4", 0, false));
		table.put(List.of("c11", 0, false));
		table.get("e");
		table.get("a7b");
		table.put(List.of("b1", 507, true));
		table.put(List.of("ccb3", 2484, false));
		table.put(List.of("daa", 0, true));
		table.put(List.of("f", 47, true));
		table.put(List.of("e", 24679, false));
		table.remove("a");
		table.put(List.of("d4", 1, true));
		table.get("bc");
		table.put(List.of("d7", 3499, true));
		table.put(List.of("ed", 43070, false));
		table.remove("d57");
		table.put(List.of("d", 413, true));
		table.put(List.of("c", 0, true));
		table.put(List.of("c3", 215, false));
		table.remove("ca");
		table.put(List.of("b0", 2, true));
		table.put(List.of("cf6", 0, true));
		table.put(List.of("f", 1, false));
		table.put(List.of("c00", 0, true));
		table.put(List.of("bb", 57, false));
		table.put(List.of("e28", 2, false));
		table.remove("b4");
		table.put(List.of("a4", 0, false));
		table.put(List.of("da", 0, true));
		table.put(List.of("a42", 0, true));
		table.put(List.of("be22", 3107, false));
		table.put(List.of("d", 0, true));
		table.put(List.of("b9", 45199, false));
		table.get("c");
		table.put(List.of("a7", 1152, false));
		table.put(List.of("b", 304, true));
		table.remove("d06");
		table.get("ec");
		table.remove("ef12");
		table.put(List.of("c", 0, true));
		table.put(List.of("d", 1217, true));
		table.put(List.of("c1f3", 18773, true));
		table.put(List.of("b", 0, false));
		table.remove("f27b");
		table.put(List.of("d", 754, true));
		table.get("ba");
		table.put(List.of("c1", 0, false));
		table.remove("fe33");
		table.put(List.of("de0", 1597, false));
		table.put(List.of("b0", 2, true));
		table.put(List.of("d", 0, true));
		table.remove("d3c8");
		table.put(List.of("e", 43890, false));
		table.put(List.of("a", 0, true));
		table.put(List.of("e0cf", 1223, true));
		table.put(List.of("e", 110, false));
		table.put(List.of("ce6e", 627, true));
		table.put(List.of("c7", 1549, false));
		table.put(List.of("c3", 34, false));
		table.get("f");
		table.put(List.of("a09", 584, true));
		table.put(List.of("ac6", 4020, true));
		table.put(List.of("a7e7", 0, false));
		table.put(List.of("c7", 0, false));
		table.put(List.of("fd", 4, true));
		table.put(List.of("d839", 9845, true));
		table.put(List.of("c", 0, true));
		table.put(List.of("e", 707, true));
		table.put(List.of("ac", 0, true));
		table.put(List.of("e42", 2252, false));
		table.remove("d");
		table.put(List.of("b", 34, false));
		table.put(List.of("b", 68, true));
		table.put(List.of("d8e3", 2, false));
		table.put(List.of("c57", 77, true));
		table.remove("c42");
		table.put(List.of("c", 72, true));
		table.put(List.of("b5", 911, false));
		table.put(List.of("b1e", 23840, true));
		table.remove("a3c");
		table.put(List.of("de", 292, false));
		table.put(List.of("d46", 95, false));
		table.put(List.of("e36", 0, true));
		table.put(List.of("ef", 1109, false));
		table.get("dc");
		table.remove("ab673");
		table.put(List.of("cf", 0, true));
		table.put(List.of("b64", 0, false));
		table.put(List.of("b", 0, false));//
		System.out.println(table.get("b"));
		table.remove("b945");
		System.out.println(table.get("b"));
		table.remove("b1b3b");
		System.out.println(table.get("b"));
		table.get("d63d");
		System.out.println(table.get("b"));
		table.remove("a");
		System.out.println(table.get("b"));
		table.put(List.of("f7", 13806, true));
		System.out.println(table.get("b"));
		table.put(List.of("d84", 0, false));
		System.out.println(table.get("b"));
		table.get("e9");
		table.get("ba");
		table.put(List.of("be", 72, false));
		System.out.println(table.get("b"));
		table.put(List.of("e605", 7, false));
		System.out.println(table.get("b"));
		table.remove("b");
		System.out.println(table.get("b"));

		System.out.println(table);
	}
}
